<% if from %>FROM <%= from %><% end %>
<% if maintainer %>MAINTAINER <%= maintainer %><% end %>

<% if environment %>ENV <% environment.each do |name, value| %><%= name.upcase %>="<%= value %>" <% end %><% end %>

<% if rocker %>MOUNT /opt/puppetlabs /etc/puppetlabs /root/.gem<% end %>

<% if labels && !labels.empty? %>LABEL <%= labels.map { |g| g.split('=') }.map { |k,v| "#{k}=\"#{v}\"" }.join(' ') %><% end %>

<% if os %>
<% if os == 'ubuntu' or os == 'debian' %>
RUN apt-get update && \
    apt-get install -y lsb-release wget && \
    wget https://apt.puppetlabs.com/puppetlabs-release-pc1-"$CODENAME".deb && \
    dpkg -i puppetlabs-release-pc1-"$CODENAME".deb && \
    rm puppetlabs-release-pc1-"$CODENAME".deb && \
    apt-get update && \
    apt-get install --no-install-recommends -y puppet-agent="$PUPPET_AGENT_VERSION"-1"$CODENAME" && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
<% elsif os == 'centos' %>
RUN rpm -Uvh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm && \
    yum upgrade -y && \
    yum update -y && \
    yum install -y puppet-agent-"$PUPPET_AGENT_VERSION" && \
    yum clean all
<% elsif os == 'alpine' %>
RUN apk add --update \
      ca-certificates \
      pciutils \
      ruby \
      ruby-irb \
      ruby-rdoc \
      && \
    echo http://dl-4.alpinelinux.org/alpine/edge/testing/ >> /etc/apk/repositories && \
    apk add --update shadow && \
    rm -rf /var/cache/apk/* && \
    gem install puppet:"$PUPPET_VERSION" facter:"$FACTER_VERSION" && \
    <%= puppet_path %> module install puppetlabs-apk

# Workaround for https://tickets.puppetlabs.com/browse/FACT-1351
RUN rm /usr/lib/ruby/gems/2.3.0/gems/facter-"$FACTER_VERSION"/lib/facter/blockdevices.rb
<% end %>
<% end %>

<% if use_puppetfile && !master %>
<% if os == 'ubuntu' or os == 'debian' %>
RUN apt-get update && \
    apt-get install -y git-core && \
    <%= gem_path %> install r10k:"$R10K_VERSION" --no-ri --no-rdoc && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
<% elsif os == 'centos' %>
RUN yum update && \
    yum install -y git && \
    <%= gem_path %> install r10k:"$R10K_VERSION" --no-ri --no-rdoc && \
    yum clean all
<% elsif os == 'alpine' %>
RUN apt-get update && \
    apk add --update git && \
    <%= gem_path %> install r10k:"$R10K_VERSION" --no-ri --no-rdoc && \
    rm -rf /var/cache/apk/*
<% end %>
COPY <%= puppetfile %> /Puppetfile
<% end %>

<% if manifest && !master %>
COPY <%= File.dirname(manifest) %> /<%= File.dirname(manifest) %>
<% end %>

<% if use_hiera && !master %>
COPY <%= hiera_config %> /hiera.yaml
COPY <%= hiera_data %> /hieradata
<% end %>

<% if autosign_token %>ARG AUTOSIGN_TOKEN<% end %>

<% if os %>
  <% if master %>
    <% if os == 'ubuntu' or os == 'debian' %>
RUN apt-get update && \
    <% if autosign_token %>printf 'custom_attributes:\n    challengePassword: "%s"\n' $AUTOSIGN_TOKEN >> /etc/puppetlabs/puppet/csr_attributes.yaml && <% end %><% if master_is_ip %>echo <%= master_host %> puppet >> /etc/hosts && <% end %>FACTER_hostname=<%= hostname %>.<%= DateTime.now.rfc3339.gsub(/[^0-9a-z]/i, '') %>.dockerbuilder <%= puppet_path %> agent --server <% if master_is_ip %>puppet<% else %><%= master_host %><% end %><% if master_port %> --masterport <%= master_port %><% end %> --verbose --onetime --no-daemonize --show_diff --summarize<% if autosign_token %> && rm /etc/puppetlabs/puppet/csr_attributes.yaml<% end %> && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
    <% elsif os == 'centos' %>
RUN yum update -y && \
    <% if autosign_token %>printf 'custom_attributes:\n    challengePassword: "%s"\n' $AUTOSIGN_TOKEN >> /etc/puppetlabs/puppet/csr_attributes.yaml && <% end %><% if master_is_ip %>echo <%= master_host %> puppet >> /etc/hosts && <% end %>FACTER_hostname=<%= hostname %>.<%= DateTime.now.rfc3339.gsub(/[^0-9a-z]/i, '') %>.dockerbuilder <%= puppet_path %> agent --server <% if master_is_ip %>puppet<% else %><%= master_host %><% end %><% if master_port %> --masterport <%= master_port %><% end %> --verbose --onetime --no-daemonize --show_diff --summarize<% if autosign_token %> && rm /etc/puppetlabs/puppet/csr_attributes.yaml<% end %> && \
    yum clean all
    <% elsif os == 'alpine' %>
RUN apk update && \
    <% if autosign_token %>printf 'custom_attributes:\n    challengePassword: "%s"\n' $AUTOSIGN_TOKEN >> /etc/puppetlabs/puppet/csr_attributes.yaml && <% end %><% if master_is_ip %>echo <%= master_host %> puppet >> /etc/hosts && <% end %>FACTER_hostname=<%= hostname %>.<%= DateTime.now.rfc3339.gsub(/[^0-9a-z]/i, '') %>.dockerbuilder <%= puppet_path %> agent --server <% if master_is_ip %>puppet<% else %><%= master_host %><% end %><% if master_port %> --masterport <%= master_port %><% end %> --verbose --onetime --no-daemonize --show_diff --summarize<% if autosign_token %> && rm /etc/puppetlabs/puppet/csr_attributes.yaml<% end %> && \
    rm -rf /var/cache/apk/*
    <% end %>
  <% else %>
    <% if os == 'ubuntu' or os == 'debian' %>
RUN apt-get update && \
    <% if use_puppetfile %><%= r10k_path %> puppetfile install --moduledir /etc/puppetlabs/code/modules && <% end %> FACTER_hostname=<%= hostname %> <%= puppet_path %> apply <%= manifest %> --verbose --show_diff --summarize <% if use_hiera %>--hiera_config=/hiera.yaml<% end %> --app_management true && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
    <% elsif os == 'centos' %>
RUN yum update -y && \
    <% if use_puppetfile %><%= r10k_path %> puppetfile install --moduledir /etc/puppetlabs/code/modules && <% end %> FACTER_hostname=<%= hostname %> <%= puppet_path %> apply <%= manifest %> --verbose --show_diff --summarize <% if use_hiera %>--hiera_config=/hiera.yaml<% end %> --app_management true && \
    yum clean all
    <% elsif os == 'alpine' %>
RUN apk update && \
<% if use_puppetfile %><%= r10k_path %> puppetfile install --moduledir /etc/puppetlabs/code/modules && <% end %> FACTER_hostname=<%= hostname %> <%= puppet_path %> apply <%= manifest %> --verbose --show_diff --summarize <% if use_hiera %>--hiera_config=/hiera.yaml<% end %> --app_management true && \
    rm -rf /var/cache/apk/*
    <% end %>
  <% end %>
<% end %>

<% if inventory %>
LABEL com.puppet.inventory="/inventory.json"
RUN <%= puppet_path %> module install puppetlabs-inventory && \
    <%= puppet_path %> inventory all > /inventory.json
<% end %>

<% if expose && !expose.empty? %>EXPOSE <%= expose.join(' ') %><% end %>

<% if entrypoint && !entrypoint.empty? %>ENTRYPOINT <%= entrypoint.to_s %><% end %>
<% if cmd && !cmd.empty? %>CMD <%= cmd.to_s %><% end %>

<% if rocker %>TAG <%= image_name %><% end %>
