FROM <%= from %>
<% if maintainer %>MAINTAINER <%= maintainer %><% end %>

ENV <% environment.each do |name, value| %><%= name.upcase %>="<%= value %>" <% end %>

<% if rocker %>MOUNT /opt/puppetlabs /etc/puppetlabs /root/.gem<% end %>

<% if labels %>LABEL <%= labels.split(',').map { |g| g.split('=') }.map { |k,v| "#{k}=\"#{v}\"" }.join(' ') %><% end %>

<% if os == 'ubuntu' or os == 'debian' %>
RUN apt-get update && \
    apt-get install -y lsb-release wget && \
    wget https://apt.puppetlabs.com/puppetlabs-release-pc1-"$CODENAME".deb && \
    dpkg -i puppetlabs-release-pc1-"$CODENAME".deb && \
    rm puppetlabs-release-pc1-"$CODENAME".deb && \
    apt-get update && \
    apt-get install --no-install-recommends -y puppet-agent="$PUPPET_AGENT_VERSION"-1"$CODENAME" && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
<% elsif os == 'centos' %>
RUN rpm -Uvh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm && \
    yum upgrade -y && \
    yum update -y && \
    yum install -y puppet-agent-"$PUPPET_AGENT_VERSION" && \
    yum clean all
<% elsif os == 'alpine' %>
RUN apk add --update \
      ca-certificates \
      pciutils \
      ruby \
      ruby-irb \
      ruby-rdoc \
      && \
    echo http://dl-4.alpinelinux.org/alpine/edge/testing/ >> /etc/apk/repositories && \
    apk add --update shadow && \
    rm -rf /var/cache/apk/* && \
    gem install puppet:"$PUPPET_VERSION" facter:"$FACTER_VERSION" && \
    <%= puppet_path %> module install puppetlabs-apk

# Workaround for https://tickets.puppetlabs.com/browse/FACT-1351
RUN rm /usr/lib/ruby/gems/2.3.0/gems/facter-"$FACTER_VERSION"/lib/facter/blockdevices.rb
<% end %>

<% if puppetfile %>
RUN <%= gem_path %> install r10k:"$R10K_VERSION" --no-ri --no-rdoc
COPY Puppetfile /
<% end %>

COPY <%= File.dirname(manifest) %> /<%= File.dirname(manifest) %>

<% if hiera %>
COPY hiera.yaml /
COPY hieradata /
<% end %>

<% if os == 'ubuntu' or os == 'debian' %>
RUN apt-get update && \
    <% if puppetfile %><%= r10k_path %> puppetfile install --moduledir /etc/puppetlabs/code/modules && <% end %><%= puppet_path %> apply <%= manifest %> --verbose --show_diff --summarize <% if hiera %>--hiera_config=/hiera.yaml<% end %> && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
<% elsif os == 'centos' %>
RUN yum update -y && \
    <% if puppetfile %><%= r10k_path %> puppetfile install --moduledir /etc/puppetlabs/code/modules && <% end %><%= puppet_path %> apply <%= manifest %> --verbose --show_diff --summarize <% if hiera %>--hiera_config=/hiera.yaml<% end %>&& \
    yum clean all
<% elsif os == 'alpine' %>
RUN apk update && \
    <% if puppetfile %><%= r10k_path %> puppetfile install --moduledir /etc/puppetlabs/code/modules && <% end %><%= puppet_path %> apply <%= manifest %> --verbose --show_diff --summarize <% if hiera %>--hiera_config=/hiera.yaml<% end %> && \
    rm -rf /var/cache/apk/*
<% end %>

<% unless disable_inventory %>
LABEL com.puppet.inventory="/inventory.json"
RUN <%= puppet_path %> module install puppetlabs-inventory && \
    <%= puppet_path %> inventory all > /inventory.json
<% end %>

<% if expose %>EXPOSE <%= expose.to_s.gsub(',', ' ') %><% end %>

<% if entrypoint %>ENTRYPOINT ["<%= entrypoint.split(',').to_s %>"]<% end %>
<% if cmd %>CMD <%= cmd.split(',').to_s %><% end %>

<% if rocker %>TAG <%= image_name %><% end %>
